[tox]
requires =
    tox>=4
env_list =
    py{39,310,311,312,313}

[testenv]
description = run unit tests
deps =
    pytest>=8.4
commands =
    pytest {posargs:tests}

[testenv:lint]
description = run code linting
skip_install = true
deps =
    ruff>=0.16
commands =
    ruff check vd2db
    ruff check tests
